#!/usr/bin/env bash
#display information about subdomains.

display_info () {
	dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$2.$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
	display_info "$1" "$2"
else
	display_info "$1" "www"
	display_info "$1" "lb-01"
	display_info "$1" "web-01"
	display_info "$1" "web-02"
fi
