#!/usr/bin/env bash
# configures a new Ubuntu Nginx Web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" >  /var/www/html/index.html
service nginx start
