#!/usr/bin/env bash
# this script displays all active IPv4 IPs on the machine it’s executed on.

interfaces=$(ifconfig -a | grep '^[a-zA-Z]' | awk '{print $1}')

for interface in $interfaces; do
	ipv4_addresses=$(ifconfig "$interface" | grep -oP 'inet \K\S+')
	if [ -n "$ipv4_addresses" ]; then
		echo "$ipv4_addresses"
	fi
done
